### ISSUE TITLE
Cannot parse special characters correctly

### ISSUE THREAD

**Issue by zhangbc97** [databendcloud/databend-sqlalchemy#1]
Version: 
databend-sqlalchemy 0.2.4
databend-py 0.4.2

The password cannot be parsed correctly if it contains special characters such as `#`, `/`, etc.
This appears to be due to urlparse's mechanism.
Attempting to encode special characters using urlencode will not solve this problem either.

```
from sqlalchemy import create_engine
engine = create_engine('databend://zhangbc:zhangbc%2F123@127.0.0.1:8000')  # encode `#` to %23
con = engine.connect()
```
Got 
`ValueError: Port could not be cast to integer value as 'zhangbc'`

**Comment by hantmac** [comment]
Thanks for your report! I will fix it as soon as possible.

**Comment by zhangbc97** [comment]
thanks

**Comment by hantmac** [comment]
Hi @zhangbc97 , I digged into this issue and not found a effective way to solve it. But you can use :

```
from urllib.parse import quote
user = quote(user)  # e.g. user#001
password = quote(password)  # e.g. P@ssw0rd#
url = f"{dialect}://{user}:{password}@{host}:{port}/{db}..."
```

can solve this problem.

**Comment by zhangbc97** [comment]
thanks!
